version: '3.8'

services:
  zookeeper:
    image: zookeeper:3.6.3
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.6.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  mysql_user:
    image: mysql:8.0.33
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: studystream
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: shadow
      MYSQL_PASSWORD: 1234

  mysql_mail:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: mail
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: shadow
      MYSQL_PASSWORD: 1234

  postgresql_auth:
    image: postgres:16.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: studystream
      POSTGRES_USER: shadow
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

  postgresql_course:
    image: postgres:16.2
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: courseservice
      POSTGRES_USER: shadow
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_course_data:/var/lib/postgresql/data

volumes:
  postgres_auth_data:
  postgres_course_data:
