global:
  scrape_interval: 5s

  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.0.170:8083']